DROP DATABASE IF EXISTS project2;
CREATE DATABASE project2;
USE project2;

-- create the megatable for the database
DROP TABLE IF EXISTS megatable;
CREATE TABLE megatable(
X1 VARCHAR(255),
CMPLNT_NUM VARCHAR(255),
CMPLNT_FR_DT VARCHAR(255),
CMPLNT_FR_TM VARCHAR(255),
CMPLNT_TO_DT VARCHAR(255),
CMPLNT_TO_TM VARCHAR(255),
ADDR_PCT_CD VARCHAR(255),
RPT_DT VARCHAR(255),
KY_CD VARCHAR(255),
OFNS_DESC VARCHAR(255),
PD_CD VARCHAR(255),
PD_DESC VARCHAR(255),
CRM_ATPT_CPTD_CD VARCHAR(255),
LAW_CAT_CD VARCHAR(255),
BORO_NM VARCHAR(255),
LOC_OF_OCCUR_DESC VARCHAR(255),
PREM_TYP_DESC VARCHAR(255),
JURIS_DESC VARCHAR(255),
JURISDICTION_CODE VARCHAR(255),
PARKS_NM VARCHAR(255),
HADEVELOPT VARCHAR(255),
HOUSING_PSA VARCHAR(255),
X_COORD_CD VARCHAR(255),
Y_COORD_CD VARCHAR(255),
SUSP_AGE_GROUP VARCHAR(255),
SUSP_RACE VARCHAR(255),
SUSP_SEX VARCHAR(255),
TRANSIT_DISTRICT VARCHAR(255),
Latitude VARCHAR(255),
Longitude VARCHAR(255),
Lat_Lon VARCHAR(255),
PATROL_BORO VARCHAR(255),
STATION_NAME VARCHAR(255),
VIC_AGE_GROUP VARCHAR(255),
VIC_RACE VARCHAR(255),
VIC_SEX VARCHAR(255)
);

-- read in the data for the project
LOAD DATA LOCAL INFILE '/Users/tonnarcastellano/Desktop/police.csv'
INTO TABLE megatable
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

SELECT * 
from megatable
limit 100;
